package controllerPkg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-28T11:56:21.466-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ControllerClassService", 
                  wsdlLocation = "http://localhost:8080/ControllerWS/services/ControllerClassPort?wsdl",
                  targetNamespace = "http://logic/") 
public class ControllerClassService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://logic/", "ControllerClassService");
    public final static QName ControllerClassPort = new QName("http://logic/", "ControllerClassPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ControllerWS/services/ControllerClassPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ControllerClassService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ControllerWS/services/ControllerClassPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ControllerClassService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ControllerClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControllerClassService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ControllerClassService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ControllerClassService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ControllerClassService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ControllerWSSEI
     */
    @WebEndpoint(name = "ControllerClassPort")
    public ControllerWSSEI getControllerClassPort() {
        return super.getPort(ControllerClassPort, ControllerWSSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControllerWSSEI
     */
    @WebEndpoint(name = "ControllerClassPort")
    public ControllerWSSEI getControllerClassPort(WebServiceFeature... features) {
        return super.getPort(ControllerClassPort, ControllerWSSEI.class, features);
    }

}
