
package controllerPkg;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-28T11:56:21.390-05:00
 * Generated source version: 3.1.12
 * 
 */
public final class ControllerWSSEI_ControllerClassPort_Client {

    private static final QName SERVICE_NAME = new QName("http://logic/", "ControllerClassService");

    private ControllerWSSEI_ControllerClassPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ControllerClassService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ControllerClassService ss = new ControllerClassService(wsdlURL, SERVICE_NAME);
        ControllerWSSEI port = ss.getControllerClassPort();  
        
       /* {
        System.out.println("Invoking start...");
        java.lang.String _start_webContext = "_start_webContext-471741099";
        boolean _start__return = port.start(_start_webContext);
        System.out.println("start.result=" + _start__return);


        }*/
        {
            System.out.println("Invoking getNextEndpoint...");
            java.lang.String _getNextEndpoint__return = port.getNextEndpoint();
            System.out.println("getNextEndpoint.result=" + _getNextEndpoint__return);
            _getNextEndpoint__return = port.getNextEndpoint();
            System.out.println("getNextEndpoint.result=" + _getNextEndpoint__return);
            _getNextEndpoint__return = port.getNextEndpoint();
            System.out.println("getNextEndpoint.result=" + _getNextEndpoint__return);
            _getNextEndpoint__return = port.getNextEndpoint();
            System.out.println("getNextEndpoint.result=" + _getNextEndpoint__return);
            _getNextEndpoint__return = port.getNextEndpoint();
            System.out.println("getNextEndpoint.result=" + _getNextEndpoint__return);


            }
   /*     {
        System.out.println("Invoking stop...");
        java.lang.String _stop_webContext = "_stop_webContext-496246192";
        boolean _stop__return = port.stop(_stop_webContext);
        System.out.println("stop.result=" + _stop__return);


        }*/

        System.exit(0);
    }

}
