
package logic.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 26 15:12:40 CDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "duplicateWS", namespace = "http://logic/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "duplicateWS", namespace = "http://logic/", propOrder = {"ws", "destinationManagerURL", "destinationWSDLAddress"})

public class DuplicateWS {

    @XmlElement(name = "ws")
    private logic.WS ws;
    @XmlElement(name = "destinationManagerURL")
    private java.lang.String destinationManagerURL;
    @XmlElement(name = "destinationWSDLAddress")
    private java.lang.String destinationWSDLAddress;

    public logic.WS getWs() {
        return this.ws;
    }

    public void setWs(logic.WS newWs)  {
        this.ws = newWs;
    }

    public java.lang.String getDestinationManagerURL() {
        return this.destinationManagerURL;
    }

    public void setDestinationManagerURL(java.lang.String newDestinationManagerURL)  {
        this.destinationManagerURL = newDestinationManagerURL;
    }

    public java.lang.String getDestinationWSDLAddress() {
        return this.destinationWSDLAddress;
    }

    public void setDestinationWSDLAddress(java.lang.String newDestinationWSDLAddress)  {
        this.destinationWSDLAddress = newDestinationWSDLAddress;
    }

}

