
package logic.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Wed Jul 26 15:12:40 CDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "undeploy", namespace = "http://logic/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "undeploy", namespace = "http://logic/", propOrder = {"ws", "tomcatManagerURL"})

public class Undeploy {

    @XmlElement(name = "ws")
    private logic.WS ws;
    @XmlElement(name = "tomcatManagerURL")
    private java.lang.String tomcatManagerURL;

    public logic.WS getWs() {
        return this.ws;
    }

    public void setWs(logic.WS newWs)  {
        this.ws = newWs;
    }

    public java.lang.String getTomcatManagerURL() {
        return this.tomcatManagerURL;
    }

    public void setTomcatManagerURL(java.lang.String newTomcatManagerURL)  {
        this.tomcatManagerURL = newTomcatManagerURL;
    }

}

