
package logic.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Sun Aug 13 18:20:36 CDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "getNextEndpointResponse", namespace = "http://logic/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNextEndpointResponse", namespace = "http://logic/")

public class GetNextEndpointResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

