package migration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-26T15:22:03.954-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "MigratorWS", 
                  wsdlLocation = "http://149.149.134.241:8080/MigratorWS/services/MigratorWSPort?wsdl",
                  targetNamespace = "http://logic/") 
public class MigratorWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://logic/", "MigratorWS");
    public final static QName MigratorWSPort = new QName("http://logic/", "MigratorWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://149.149.134.241:8080/MigratorWS/services/MigratorWSPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MigratorWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/MigratorWS/services/MigratorWSPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MigratorWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MigratorWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MigratorWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MigratorWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MigratorWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MigratorWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MigratorWSPortType
     */
    @WebEndpoint(name = "MigratorWSPort")
    public MigratorWSPortType getMigratorWSPort() {
        return super.getPort(MigratorWSPort, MigratorWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MigratorWSPortType
     */
    @WebEndpoint(name = "MigratorWSPort")
    public MigratorWSPortType getMigratorWSPort(WebServiceFeature... features) {
        return super.getPort(MigratorWSPort, MigratorWSPortType.class, features);
    }

}
